### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by stas**
Hey @hmac!

First of all, thanks for releasing this :bow: 

I was playing a bit with the gem and I thought I should take care of those automated PRs Github sent.

Hopefully you'll find these useful.

### CODE REVIEW

**Comment by hmac** [comment]
@stas this is fantastic, thank you!

**Comment by stas** [comment]
Thanks @hmac !

I'll prepare some more updates related to the CI failure (sorry, missed it :see_no_evil: )

**Comment by hmac** [comment]
I think that’s partially down to a flaky test, but any improvements you want to make are very appreciated!

**Comment by stas** [comment]
I'll send things over and you can review them...

**Pull request merged**
