### PR TITLE
Shave some deps

### PR DESCRIPTION
**Pull request by stas**
Some minor improvements post #116 

* The flanky test seems to be caused by our own _threaded pool_, which is now replaced by the `concurrent-ruby` implementation (it's a dependency of the active-support via active-PACK gems).
* ActiveJob has no direct requires.
 * ActiveSupport _seconds_ from an interval is not needed for Sequel, so we assume the retry interval is always in seconds (`interval.to_i`).

@hmac please take a look and let me know if I didn't miss anything :see_no_evil: 

Thank you!

### CODE REVIEW

**Comment by hmac** [comment]
Thanks for this! Really great to see that test fixed. I have just a couple of comments:

- If we're removing the CircleCI badge, it would be great to replace it with a GitHub Actions one (https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository)
- I'm not sure if the migration in `lib/what/migrations/v1.rb` will work with AR versions < 5, so it may not be safe to remove that lower bound. What do you think?
- I like to keep `pry` around as a development dep in things because it's so useful to have when debugging, so it would be great to keep that unless there's a good reason to drop it

Otherwise, this looks super great 👍

**Comment by stas** [comment]
> I'm not sure if the migration in `lib/what/migrations/v1.rb` will work with AR versions < 5, so it may not be safe to remove that lower bound. What do you think?

Do we have any interest in maintaining rails 4 btw? If so, I could add support for it (unfortunately I have no recent projects on rails 4).

**Comment by stas** [comment]
@hmac I added support for rails 4 and reverted the changes you requested.

Btw, it would be nice to release it as a gem, consider using the name `what.rb` :hugs:

**Comment by hmac** [comment]
I've just checked Rails' [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html) and they no longer support Rails 4, so I'm happy to not support it in What either. Given that, I think it'll be simpler if we just leave the AR dependency at `>= 5.0` and not worry about it any further (i.e. I don't think we need to add any logic around the rails version).

Sorry about the back on forth on this PR - after this change I think it's definitely ready to go in :)

I would like to release What as a gem, but I wanted to make sure it was stable first. The retry strategy design is a little bit clunky and could use some improvement, amonst other things. But if you're finding it useful then that's definitely a point in favour of releasing it properly!

**Comment by stas** [comment]
Sweet, it's updated now.

I'll let you know how it goes after running some tests. Looking into replacing pq in fact... Thank you!

**Comment by hmac** [comment]
👌 thanks!

**Pull request merged**
